/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include <ifxCpu_Irq.h>
#include "IfxScuWdt.h"

#include "SmartCar_GPIO.h"
#include "SmartCar_Systick.h"
#include "SmartCar_Oled.h"
#include "SmartCar_Systick.h"
#include "SmartCar_PIT.h"

#include "Function.h"
#include "Menu.h"

#pragma section all "cpu0_dsram"
//IfxCpu_syncEvent g_cpuSyncEvent;

int core0_main(void)
{
    /** 关闭总中断*/
    IfxCpu_disableInterrupts();
    /** 初始化时钟*/
    get_clk();
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /** 初始化OLED*/
    SmartCar_Oled_Init();
    SmartCar_Buffer_Upload((const uint8 *)DISP_image_HSIC_lilac);
    Delay_ms(STM0, 1000);

    /** 初始化菜单 */
    Menu_Init();

    /** ↓↓↓↓↓在这里初始化GPIO↓↓↓↓↓*/

    /** ↑↑↑↑↑在这里初始化GPIO↑↑↑↑↑*/

    SmartCar_OLED_Fill(0);


    /** Flash读  */

    /* 上电次数 */
    Times = Page_Read(5, 0, uint32);
    ++Times;
    uint32 buff1[1024] = {Times, 0};
    Sector_Erase(5);
    Page_Program(5, 0, buff1);

    /* 发动机读取 */
    Current_Gear = Page_Read(0, 0, uint32);
    FIVEMENU_readFlash(); // Flash读入数据

    /** 显示菜单 */
    Display(MenuPoint, selectItem_current, selectItem_hidden, selectItem);
    /** 开启总中断*/
    IfxCpu_enableInterrupts();

    /** 主循环 */
    while(TRUE)
    {
        // 获取五项按键
        key = Get_Operation();

        if(key != 0) {
            // 根据按键，更新菜单指针
            Run_Menus(key);
            // 每次显示前清屏
            SmartCar_OLED_Fill(0);
            // 显示菜单
            Display(MenuPoint, selectItem_current, selectItem_hidden, selectItem);
        }
    }
}


#pragma section all restore
